allowBuilds:
  '@prisma/engines': true
  core-js: false
  esbuild: true
  msgpackr-extract: set this to true or false
  prisma: true
  sharp: false
  unrs-resolver: false
  workerd: set this to true or false

minimumReleaseAgeExclude:
  - posthog-js@1.430.3

overrides:
  deepmerge-ts: '>=8.0.0'
  mysql2: '>=3.24.3'
